spring.flyway.locations=classpath:db/migration,classpath:db/testdata

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

spring.profiles.active=dev

spring.servlet.multipart.max-file-size=60MB
spring.servlet.multipart.max-request-size=60MB

algafood.storage.tipo=S3

algafood.storage.local.diretorio-fotos=${LOCAL_STORAGE}

algafood.storage.s3.id-chave-acesso=${AWS_ACCESS_KEY_ID}
algafood.storage.s3.id-chave-acesso-secreta=${AWS_SECRET_ACCESS_KEY}
algafood.storage.s3.bucket=teste-algafood-imagens
algafood.storage.s3.regioes=us-east-1
algafood.storage.s3.diretorio-fotos=catalogo

#Autenticacao servidor SMTP - Sendgrid
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${EMAIL_ACCESS_KEY}